apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "vishwkore@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "myfk sbiq kqgo ijub"
type: Opaque

# Passw0rd@1234
